spring:
  datasource:
    url: jdbc:postgresql://dev-db-host:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

logging:
  level:
    root: INFO
    org.example.csa_backend: INFO
