-- V11: subscription state-transition history, for the admin "구독 상태 변경 이력"
-- timeline (csa_adm_backend reads it in a separate round; csa_backend owns the
-- schema and writes the rows). The subscription table keeps exactly one row per
-- subscription and is UPDATEd in place on every renewal/notification, so the
-- previous state is lost -- this table is the append-only ledger of those
-- transitions.
--
-- Append-only, audit-style log with no soft delete/update lifecycle, so this
-- mirrors the simpler admin_audit_log (V8) / fairytale_download_log (V9)
-- pattern (plain created_at) rather than the full BaseEntity audit columns
-- (cre_dt/cre_id/mod_dt/mod_id/del_yn) used by domain entities.
--
-- previous_* columns are nullable: the first row of a subscription (source =
-- 'CREATED') has no prior state. In Postgres a CHECK evaluating to NULL passes,
-- so the previous_status IN (...) constraint below still admits NULL; the
-- is null branch is written out only to make that explicit.
--
-- status values and their varchar(12) width mirror subscription.status (V2)
-- exactly so both tables can be filtered/joined with the same enum vocabulary.
--
-- Identifiers are unquoted lowercase snake_case to match Hibernate's runtime
-- PhysicalNamingStrategySnakeCaseImpl (Spring Boot 4 default), so ddl-auto:
-- validate passes against this schema. Created in the schema configured by
-- spring.flyway.default-schema (front).

create table subscription_history (
    id                  bigint generated by default as identity,
    subscription_id     bigint not null,
    previous_status     varchar(12) check (previous_status is null
                            or previous_status in ('ACTIVE', 'EXPIRED', 'CANCELED', 'GRACE')),
    new_status          varchar(12) not null check (new_status in ('ACTIVE', 'EXPIRED', 'CANCELED', 'GRACE')),
    previous_period_end timestamp(6),
    new_period_end      timestamp(6),
    previous_auto_renew varchar(1) check (previous_auto_renew is null
                            or previous_auto_renew in ('Y', 'N')),
    new_auto_renew      varchar(1) not null check (new_auto_renew in ('Y', 'N')),
    source              varchar(20) not null check (source in (
                            'CREATED', 'VERIFICATION', 'STORE_NOTIFICATION', 'SUPERSEDED', 'EXPIRY_SWEEP')),
    created_at          timestamp(6) not null default now(),
    primary key (id)
);

alter table if exists subscription_history
    add constraint fk_subscription_history_subscription
    foreign key (subscription_id) references subscription;

-- Primary admin access path is "one subscription's history in chronological
-- order", so the composite covers both the lookup and the ordering (and its
-- leading column still serves plain subscription_id filters).
create index idx_subscription_history_subscription
    on subscription_history (subscription_id, created_at);

-- Global "recent subscription changes" admin feed.
create index idx_subscription_history_created_at
    on subscription_history (created_at);
