-- V1 baseline: full schema reflecting current JPA entities (11 tables + 1 join table).
-- Identifiers are unquoted lowercase to match Hibernate's runtime PhysicalNamingStrategySnakeCaseImpl
-- (Spring Boot 4 default), so that ddl-auto: validate passes against this schema.
-- Objects are created in the schema configured by spring.flyway.default-schema (front).

create table users (
    id          bigint generated by default as identity,
    email       varchar(255) unique,
    password    varchar(255),
    provider    varchar(255),
    provider_id varchar(255),
    name        varchar(255),
    locale      varchar(255),
    created_at  timestamp(6) not null,
    primary key (id),
    unique (provider, provider_id)
);

create table refresh_tokens (
    id         bigint generated by default as identity,
    user_id    bigint not null unique,
    token_hash varchar(255) not null,
    expires_at timestamp(6) not null,
    primary key (id)
);

create table user_settings (
    id                bigint generated by default as identity,
    user_id           bigint not null unique,
    locale            varchar(5) not null,
    text_noti_yn      varchar(1) not null,
    push_noti_yn      varchar(1) not null,
    subscription_tier varchar(10) not null,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6) not null,
    primary key (id)
);

create table term_agreements (
    id           bigint generated by default as identity,
    user_id      bigint not null,
    term_type    varchar(20) not null check (term_type in ('SERVICE', 'FINANCE', 'PRIVACY')),
    term_version varchar(10) not null,
    agreed_at    timestamp(6) not null,
    primary key (id),
    unique (user_id, term_type, term_version)
);

create table favorites (
    id           bigint generated by default as identity,
    user_id      bigint not null,
    fairytale_id bigint not null,
    created_at   timestamp(6) not null,
    primary key (id),
    unique (user_id, fairytale_id)
);

create table fairytales (
    id              bigint generated by default as identity,
    title           varchar(200) not null,
    title_ja        varchar(200),
    description     varchar(500),
    description_ja  varchar(500),
    rating          float(53),
    color_hex       varchar(7),
    theme_tag       varchar(50),
    is_theme        varchar(1) not null,
    is_new          varchar(1) not null,
    is_recommended  varchar(1) not null,
    cre_dt          timestamp(6) not null,
    cre_id          varchar(50) not null,
    mod_dt          timestamp(6),
    mod_id          varchar(50),
    del_yn          varchar(1) not null default 'N',
    primary key (id)
);

create table fairytale_details (
    id              bigint generated by default as identity,
    fairytale_id    bigint not null unique,
    author_ko       varchar(100) not null,
    author_ja       varchar(100),
    age_range       varchar(20) not null,
    duration_min    integer not null,
    page_count      integer not null,
    full_content_ko TEXT,
    full_content_ja TEXT,
    cre_dt          timestamp(6) not null,
    cre_id          varchar(50) not null,
    mod_dt          timestamp(6),
    mod_id          varchar(50),
    del_yn          varchar(1) not null default 'N',
    primary key (id)
);

create table categories (
    id           bigint generated by default as identity,
    category_key varchar(50) not null unique,
    name_ko      varchar(100) not null,
    name_ja      varchar(100) not null,
    cre_dt       timestamp(6) not null,
    cre_id       varchar(50) not null,
    mod_dt       timestamp(6),
    mod_id       varchar(50),
    del_yn       varchar(1) not null default 'N',
    primary key (id)
);

create table fairytale_categories (
    fairytale_id bigint not null,
    category_id  bigint not null
);

create table characters (
    id       bigint generated by default as identity,
    user_id  bigint not null,
    name     varchar(50) not null,
    variants varchar(100) not null,
    cre_dt   timestamp(6) not null,
    cre_id   varchar(50) not null,
    mod_dt   timestamp(6),
    mod_id   varchar(50),
    del_yn   varchar(1) not null default 'N',
    primary key (id)
);

create table ai_fairytales (
    id            bigint generated by default as identity,
    user_id       bigint,
    title         varchar(300) not null,
    settings      varchar(200),
    genre         varchar(50),
    theme         varchar(50),
    chapter_count integer not null,
    voice_type    varchar(20),
    language      varchar(5) not null,
    format        varchar(10) not null,
    status        varchar(20) not null,
    shared        varchar(1) not null,
    cre_dt        timestamp(6) not null,
    cre_id        varchar(50) not null,
    mod_dt        timestamp(6),
    mod_id        varchar(50),
    del_yn        varchar(1) not null default 'N',
    primary key (id)
);

create table ai_fairytale_pages (
    id              bigint generated by default as identity,
    ai_fairytale_id bigint not null,
    page_index      integer not null,
    text            TEXT not null,
    image_url       varchar(1000),
    audio_url       varchar(1000),
    cre_dt          timestamp(6) not null,
    cre_id          varchar(50) not null,
    mod_dt          timestamp(6),
    mod_id          varchar(50),
    del_yn          varchar(1) not null default 'N',
    primary key (id)
);

alter table if exists refresh_tokens
    add constraint fk_refresh_tokens_user
    foreign key (user_id) references users;

alter table if exists user_settings
    add constraint fk_user_settings_user
    foreign key (user_id) references users;

alter table if exists term_agreements
    add constraint fk_term_agreements_user
    foreign key (user_id) references users;

alter table if exists favorites
    add constraint fk_favorites_user
    foreign key (user_id) references users;

alter table if exists favorites
    add constraint fk_favorites_fairytale
    foreign key (fairytale_id) references fairytales;

alter table if exists fairytale_details
    add constraint fk_fairytale_details_fairytale
    foreign key (fairytale_id) references fairytales;

alter table if exists fairytale_categories
    add constraint fk_fairytale_categories_fairytale
    foreign key (fairytale_id) references fairytales;

alter table if exists fairytale_categories
    add constraint fk_fairytale_categories_category
    foreign key (category_id) references categories;

alter table if exists characters
    add constraint fk_characters_user
    foreign key (user_id) references users;

alter table if exists ai_fairytales
    add constraint fk_ai_fairytales_user
    foreign key (user_id) references users;

alter table if exists ai_fairytale_pages
    add constraint fk_ai_fairytale_pages_ai_fairytale
    foreign key (ai_fairytale_id) references ai_fairytales;
