-- V2: IAP single-payment subscription domain (Phase 1 schema only).
-- Identifiers are unquoted lowercase snake_case to match Hibernate's runtime
-- PhysicalNamingStrategySnakeCaseImpl (Spring Boot 4 default), so ddl-auto: validate
-- passes against this schema. Created in the schema configured by
-- spring.flyway.default-schema (front). Column types/constraints mirror the
-- Subscription JPA entity exactly.

create table subscription (
    id                      bigint generated by default as identity,
    user_id                 bigint not null,
    platform                varchar(10) not null check (platform in ('APPLE', 'GOOGLE')),
    product_id              varchar(255) not null,
    original_transaction_id varchar(255),
    status                  varchar(12) not null check (status in ('ACTIVE', 'EXPIRED', 'CANCELED', 'GRACE')),
    current_period_end      timestamp(6),
    auto_renew              varchar(1) not null,
    environment             varchar(10) not null check (environment in ('SANDBOX', 'PRODUCTION')),
    created_at              timestamp(6) not null,
    updated_at              timestamp(6) not null,
    primary key (id)
);

create index idx_subscription_user
    on subscription (user_id);

create unique index ux_subscription_original_transaction_id
    on subscription (original_transaction_id);

alter table if exists subscription
    add constraint fk_subscription_user
    foreign key (user_id) references users;
