alter table fairytales
    add column character_supported boolean not null default false;

alter table fairytale_details
    add column content_version varchar(50);

create table curated_fairytale_pages (
    id bigint generated by default as identity,
    fairytale_id bigint not null,
    page_index integer not null,
    image_url varchar(1000) not null,
    text_ko text not null,
    text_ja text not null,
    content_version varchar(50) not null,
    placement_x float(53),
    placement_y float(53),
    placement_width float(53),
    placement_height float(53),
    placement_z_index integer,
    placement_pose varchar(50),
    placement_flip_x boolean,
    cre_dt timestamp(6) not null,
    cre_id varchar(50) not null,
    mod_dt timestamp(6),
    mod_id varchar(50),
    del_yn varchar(1) not null default 'N',
    primary key (id),
    unique (fairytale_id, page_index),
    constraint ck_curated_page_placement check (
        (placement_x is null and placement_y is null and placement_width is null and placement_height is null
            and placement_z_index is null and placement_pose is null and placement_flip_x is null)
        or
        (placement_x between 0 and 1 and placement_y between 0 and 1
            and placement_width between 0 and 1 and placement_height between 0 and 1
            and placement_x + placement_width <= 1 and placement_y + placement_height <= 1
            and placement_z_index is not null and placement_pose is not null and placement_flip_x is not null)
    )
);

create table curated_fairytale_audios (
    id bigint generated by default as identity,
    page_id bigint not null,
    voice_type varchar(20) not null,
    locale varchar(5) not null,
    audio_url varchar(1000) not null,
    cre_dt timestamp(6) not null,
    cre_id varchar(50) not null,
    mod_dt timestamp(6),
    mod_id varchar(50),
    del_yn varchar(1) not null default 'N',
    primary key (id),
    unique (page_id, voice_type, locale)
);

alter table curated_fairytale_pages
    add constraint fk_curated_fairytale_pages_fairytale
    foreign key (fairytale_id) references fairytales;

alter table curated_fairytale_audios
    add constraint fk_curated_fairytale_audios_page
    foreign key (page_id) references curated_fairytale_pages;
