-- V7: new report domain for the upcoming admin site (report content/users, admin review workflow).
-- Identifiers are unquoted lowercase snake_case to match Hibernate's runtime
-- PhysicalNamingStrategySnakeCaseImpl (Spring Boot 4 default), so ddl-auto: validate
-- passes against this schema. Created in the schema configured by
-- spring.flyway.default-schema (front). Column types/constraints mirror the
-- Report JPA entity (incl. inherited BaseEntity audit columns) exactly.

create table reports (
    id          bigint generated by default as identity,
    reporter_id bigint not null,
    target_type varchar(20) not null,
    target_id   bigint not null,
    reason      varchar(50) not null,
    detail      text,
    status      varchar(20) not null default 'PENDING',
    admin_note  text,
    resolved_by bigint,
    resolved_at timestamp(6),
    cre_dt      timestamp(6) not null,
    cre_id      varchar(50) not null,
    mod_dt      timestamp(6),
    mod_id      varchar(50),
    del_yn      varchar(1) not null default 'N',
    primary key (id)
);

alter table if exists reports
    add constraint fk_reports_reporter
    foreign key (reporter_id) references users;

alter table if exists reports
    add constraint fk_reports_resolved_by
    foreign key (resolved_by) references users;

create index idx_reports_status on reports (status);
create index idx_reports_target on reports (target_type, target_id);
