-- V8: admin audit log for csa_adm_frontend destructive/high-impact actions
-- (user suspend/activate, fairytale unshare/delete, report resolve/reject).
-- Written and read exclusively by csa_adm_backend; csa_backend only owns the
-- migration (schema ownership), no entity is added on this side.
-- Identifiers are unquoted lowercase snake_case to match Hibernate's runtime
-- PhysicalNamingStrategySnakeCaseImpl (Spring Boot 4 default), so ddl-auto: validate
-- passes against this schema. Created in the schema configured by
-- spring.flyway.default-schema (front).

create table admin_audit_log (
    id            bigint generated by default as identity,
    admin_user_id bigint not null,
    admin_email   varchar(255),
    action        varchar(50) not null,
    target_type   varchar(20) not null,
    target_id     bigint not null,
    detail        text,
    created_at    timestamp(6) not null default now(),
    primary key (id)
);

alter table if exists admin_audit_log
    add constraint fk_admin_audit_log_admin_user
    foreign key (admin_user_id) references users;

create index idx_admin_audit_log_target on admin_audit_log (target_type, target_id);
create index idx_admin_audit_log_admin_user on admin_audit_log (admin_user_id);
create index idx_admin_audit_log_created_at on admin_audit_log (created_at);
