-- V9: fairytale download event log, for the upcoming admin "which fairytales/
-- categories do subscribers download offline most" analytics (csa_adm_backend,
-- separate round). Append-only, audit-style log -- no soft delete/update
-- lifecycle -- so this mirrors the simpler admin_audit_log (V8) pattern
-- (plain created_at) rather than the full BaseEntity audit columns
-- (cre_dt/cre_id/mod_dt/mod_id/del_yn) used by domain entities.
--
-- Polymorphic target: as of this migration, csa_frontend's actual download
-- flow (download_manager.dart) only ever downloads AiFairytale (user-generated
-- fairytale, no category). The curated Fairytale (has categories via
-- fairytale_categories) is not yet wired to offline download in the frontend,
-- but category-based popularity aggregation is a stated product requirement,
-- so this table supports both target types now via an explicit discriminator
-- plus two nullable FKs (exactly one populated per row, enforced by CHECK).
-- This lets a later frontend round start logging curated Fairytale downloads
-- without another migration, while csa_adm_backend's aggregation query can
-- join fairytale_categories only for target_type = 'FAIRYTALE' rows.
--
-- Identifiers are unquoted lowercase snake_case to match Hibernate's runtime
-- PhysicalNamingStrategySnakeCaseImpl (Spring Boot 4 default), so ddl-auto:
-- validate passes against this schema. Created in the schema configured by
-- spring.flyway.default-schema (front).

create table fairytale_download_log (
    id              bigint generated by default as identity,
    user_id         bigint not null,
    target_type     varchar(20) not null check (target_type in ('FAIRYTALE', 'AI_FAIRYTALE')),
    fairytale_id    bigint,
    ai_fairytale_id bigint,
    format          varchar(10) not null check (format in ('slide', 'video')),
    created_at      timestamp(6) not null default now(),
    primary key (id),
    check (
        (target_type = 'FAIRYTALE' and fairytale_id is not null and ai_fairytale_id is null) or
        (target_type = 'AI_FAIRYTALE' and ai_fairytale_id is not null and fairytale_id is null)
    )
);

alter table if exists fairytale_download_log
    add constraint fk_fairytale_download_log_user
    foreign key (user_id) references users;

alter table if exists fairytale_download_log
    add constraint fk_fairytale_download_log_fairytale
    foreign key (fairytale_id) references fairytales;

alter table if exists fairytale_download_log
    add constraint fk_fairytale_download_log_ai_fairytale
    foreign key (ai_fairytale_id) references ai_fairytales;

create index idx_fairytale_download_log_fairytale on fairytale_download_log (fairytale_id);
create index idx_fairytale_download_log_ai_fairytale on fairytale_download_log (ai_fairytale_id);
create index idx_fairytale_download_log_user on fairytale_download_log (user_id);
create index idx_fairytale_download_log_created_at on fairytale_download_log (created_at);
